trektribe/api/urls.py
from rest_framework.routers import DefaultRouter

from .views import EventViewSet, QuoteViewSet

router = DefaultRouter()
router.register("events", EventViewSet)
router.register("quotes", QuoteViewSet)

trektribe/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from . import views
from .sitemaps import EventSitemap

urlpatterns = [
    path("", views.event_list, name="event_list"),
    path("event/<int:pk>/", views.event_detail, name="event_detail"),
    path("info/", views.info, name="info"),
    path("users/<int:pk>/", views.user_profile_detail, name="user_profile_detail"),
    path(
        "trektribe-sitemap.xml",
        sitemap,
        {
            "sitemaps": {
                "events": EventSitemap,
            },
        },
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from trektribe.api.urls import router as trektribe_router

urlpatterns = [
    path(f"{settings.ADMIN_BASE_URL}/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("api/trektribe/", include((trektribe_router.urls, "api-trektribe"))),
    path("", include("trektribe.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trektribe/models.py
from datetime import date

from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from django.db import models

User = get_user_model()


class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Event(BaseModel):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Utente organizzatore"
    )
    date = models.DateField(verbose_name="Data", null=True, blank=True)
    title = models.CharField(
        verbose_name="Titolo",
        max_length=128,
    )
    short_description = models.TextField(
        verbose_name="Breve descrizione",
        max_length=500,
        help_text="Visualizzata nell'elenco escursioni",
    )
    whatsapp_group = models.URLField(
        verbose_name="Link gruppo WhatsApp dedicato",
        blank=True,
        help_text=(
            "Visualizzato solo se è indicata anche la data,"
            + " e fino a quello stesso giorno."
        ),
    )
    distance = models.FloatField(
        blank=True,
        null=True,
        verbose_name="Lunghezza (km)",
        help_text="Se non indicata, verrà calcolata dalla traccia GPX",
    )
    elevation_gain = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Dislivello (m)",
        help_text="Se non indicato, verrà calcolato dalla traccia GPX",
    )
    starting_altitude = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Altitudine di partenza (m)",
        help_text="Se non indicata, verrà calcolata dalla traccia GPX",
    )
    max_altitude = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Altitudine massima (m)",
        help_text="Se non indicata, verrà calcolata dalla traccia GPX",
    )
    difficulty = models.CharField(max_length=10, blank=True, verbose_name="Difficoltà")
    difficulty_details = models.TextField(
        blank=True, verbose_name="Maggiori dettagli sulla difficoltà"
    )
    #  Altitudine partenza: 890 m
    #  Altitudine massima: 1.763 m
    #  Difficoltà: E (Escursionisti)
    # info difficoltà

    description = RichTextField(verbose_name="Descrizione estesa", blank=True)
    gpx_track = models.FileField(
        verbose_name="Traccia GPX",
        upload_to="gpx_tracks/uploads/%Y/%m/%d/",
        null=True,
        blank=True,
        validators=[FileExtensionValidator(allowed_extensions=["gpx"])],
    )
    views_count = models.BigIntegerField(
        verbose_name="Contatore visualizzazioni", default=0
    )

    @property
    def is_past_due(self):
        return self.date and date.today() > self.date

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventi"

    def __str__(self) -> str:
        if self.date:
            return f"{self.date.strftime('%Y-%m-%d')} - {self.title}"
        else:
            return self.title


class Quote(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Utente")
    date = models.DateField(verbose_name="Data", default=date.today)
    quote = models.TextField(verbose_name="Citazione")
    author = models.CharField(verbose_name="Autore", max_length=128)
    likes = models.IntegerField(verbose_name="Mi piace", default=0)

    class Meta:
        verbose_name = "Citazione"
        verbose_name_plural = "Citazioni"

    def __str__(self) -> str:
        if self.date:
            return f"{self.date.strftime('%Y-%m-%d')} - {self.quote} - {self.author}"
        else:
            return f"{self.quote} - {self.author}"

trektribe/api/views.py
from rest_framework.viewsets import ReadOnlyModelViewSet

from website.paginations import DefaultLimitOffsetPagination

from ..models import Event, Quote
from .serializers import EventDetailSerializer, EventListSerializer, QuoteSerializer


class EventViewSet(ReadOnlyModelViewSet):
    queryset = Event.objects.all()
    pagination_class = DefaultLimitOffsetPagination
    serializers = {
        "list": EventListSerializer,
        "default": EventDetailSerializer,
    }
    filterset_fields = ["title"]
    search_fields = ["title", "description"]

    def get_serializer_class(self):
        return self.serializers.get(self.action, self.serializers["default"])


class QuoteViewSet(ReadOnlyModelViewSet):
    queryset = Quote.objects.all()
    pagination_class = DefaultLimitOffsetPagination
    serializer_class = QuoteSerializer
    filterset_fields = ["quote", "author"]
    search_fields = ["quote", "author"]

trektribe/views.py
from datetime import date, timedelta

from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import connection
from django.db.models import DurationField, ExpressionWrapper, F, Value
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from user_profile.models import SocialLink, UserProfile

from .models import Event


def _get_search_qs(search):
    if connection.vendor == "postgresql":
        search_vector = SearchVector(
            "title", weight="A", config="italian"
        ) + SearchVector("short_description", weight="B", config="italian")
        search_query = SearchQuery(search, config="italian")
        search_rank = SearchRank(search_vector, search_query)
        qs = Event.objects.annotate(search=search_vector, rank=search_rank).filter(
            search=search_query
        )
    else:
        search_title_qs = Event.objects.filter(title__icontains=search).annotate(
            rank=Value(1.0)
        )
        search_short_description_qs = (
            Event.objects.filter(short_description__icontains=search)
            .exclude(title__icontains=search)
            .annotate(rank=Value(0.4))
        )
        qs = search_title_qs.union(search_short_description_qs)
    return qs.order_by("-rank")


def _get_event_qs():
    today = date.today()
    two_days_ago = today - timedelta(days=2)
    now = timezone.now()

    qs = Event.objects.all()
    recent_events = (
        qs.filter(date__gte=two_days_ago)
        # .order_by("date")
        .annotate(
            custom_order1=Value(1),
            custom_order2=ExpressionWrapper(F("date") - today, DurationField()),
        )
    )
    generic_events = (
        qs.filter(date__isnull=True)
        # .order_by("-modified_date")
        .annotate(
            custom_order1=Value(2),
            custom_order2=ExpressionWrapper(now - F("modified_date"), DurationField()),
        )
    )
    past_events = (
        qs.filter(date__lt=two_days_ago)
        # .order_by("-date")
        .annotate(
            custom_order1=Value(3),
            custom_order2=ExpressionWrapper(today - F("date"), DurationField()),
        )
    )
    aggregated_events = recent_events.union(generic_events, past_events).order_by(
        "custom_order1", "custom_order2", "-modified_date"
    )
    return aggregated_events


def event_list(request):
    page = request.GET.get("page", 1)
    search = request.GET.get("search", "")

    if search:
        qs = _get_search_qs(search)
    else:
        qs = _get_event_qs()

    next_event = None
    start_index = 0
    if not search:
        next_event = qs.first()
        start_index = 1

    paginator = Paginator(qs[start_index::1], per_page=10)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        page_obj = paginator.page(1)
        page = 1
    except EmptyPage:
        # if the page is out of range, deliver the last page
        page_obj = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    page_range = page_obj.paginator.get_elided_page_range(number=page)
    return render(
        request,
        "trektribe/event_list.html",
        {
            "tab_selected": "events",
            "next_event": next_event,
            "page_obj": page_obj,
            "page_range": page_range,
            "search": search,
        },
    )


def event_detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if not request.user.is_authenticated:
        Event.objects.filter(pk=pk).update(
            views_count=event.views_count + 1,
            modified_date=event.modified_date,
        )
    return render(
        request,
        "trektribe/event_detail.html",
        {
            "tab_selected": "events",
            "event": event,
        },
    )


def info(request):
    return render(request, "trektribe/info.html", {"tab_selected": "info"})


def user_profile_detail(request, pk):
    user_profile = get_object_or_404(UserProfile, pk=pk)
    return render(
        request,
        "trektribe/user_profile_detail.html",
        {
            "user_profile": user_profile,
            "link_types_with_related_icon": SocialLink.LINK_TYPES_WITH_RELATED_ICON,
        },
    )

trektribe/templates/trektribe/base.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Massively by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html lang="it">

<head>
    {% block title %}
    <title>TrekTribe</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <link rel="icon" type="image/x-icon" href="{% static 'images/trektribe-logo-transparent.png' %}">
    {% block styles %}
    {% endblock %}
    <noscript>
        <link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" />
    </noscript>
</head>

<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper" class="fade-in">

        <!-- Intro -->
        <div id="intro">
            <h1>TREKTRIBE (beta)</h1>
            <p>
                Esplora i sentieri più belli con i tuoi amici di sempre
                o fai nuove amicizie nella nostra compagnia di appassionati di trekking.
            </p>
            <p>
                L'avventura non ha limiti quando sei in buona compagnia!
            </p>
            <!-- <ul class="actions">
                <li><a href="#header" class="button icon solid solo fa-arrow-down scrolly">Continue</a></li>
            </ul> -->
        </div>

        <!-- Header -->
        <!-- <header id="header">
            <a href="index.html" class="logo">TrekTribe</a>
        </header> -->

        <!-- Nav -->
        <nav id="nav">
            <ul class="links">
                <li{% if tab_selected == "events" %} class="active"{% endif %}>
                    <a href="{% url 'event_list' %}#main">Elenco proposte</a>
                </li>
                <li{% if tab_selected == "info" %} class="active"{% endif %}>
                    <a href="{% url 'info' %}#main">Info</a>
                </li>
            </ul>
            <ul class="icons">
                <!-- <li><a href="#" class="icon fab fa-twitter"><span class="label">Twitter</span></a></li> -->
                <!-- <li><a href="#" class="icon fab fa-facebook-f"><span class="label">Facebook</span></a></li> -->
                <li>
                    <a href="https://www.instagram.com/trek_tribe/" class="icon fab fa-instagram" target="_blank">
                        <span class="label">Instagram</span>
                    </a>
                </li>
                <li>
                    <a href="https://chat.whatsapp.com/KweLEtTDjzjLcXBpOh2t7f" class="icon fab fa-whatsapp" target="_blank">
                        <span class="label">WhatsApp</span>
                    </a>
                </li>
                <li>
                    <a href="https://github.com/TrekTribe/" class="icon fab fa-github" target="_blank">
                        <span class="label">GitHub</span>
                    </a>
                </li>
            </ul>
        </nav>

        <!-- Main -->
        <div id="main">
            <form action="{% url 'event_list' %}#main">
                <input type="text" name="search" placeholder="Cerca escursioni" value="{{ search }}" />
                {% if search and page_obj %}
                <span>{{ page_obj.paginator.count }} risultati trovati</span>
                {% endif %}
            </form>
            {% block content %}
            {% endblock %}
        </div>

        <!-- Footer -->
        <footer id="footer">
            <!-- <section>
                <form method="post" action="#">
                    <div class="fields">
                        <div class="field">
                            <label for="name">Name</label>
                            <input type="text" name="name" id="name" />
                        </div>
                        <div class="field">
                            <label for="email">Email</label>
                            <input type="text" name="email" id="email" />
                        </div>
                        <div class="field">
                            <label for="message">Message</label>
                            <textarea name="message" id="message" rows="3"></textarea>
                        </div>
                    </div>
                    <ul class="actions">
                        <li><input type="submit" value="Send Message" /></li>
                    </ul>
                </form>
            </section> -->
            <section class="split contact">
                <!-- <section class="alt">
                    <h3>Address</h3>
                    <p>1234 Somewhere Road #87257<br />
                        Nashville, TN 00000-0000</p>
                </section> -->
                <!-- <section>
                    <h3>Phone</h3>
                    <p><a href="#">(000) 000-0000</a></p>
                </section> -->
                <!-- <section>
                    <h3>Email</h3>
                    <p><a href="#">info@untitled.tld</a></p>
                </section> -->
                <section>
                    <h3>Social</h3>
                    <ul class="icons alt">
                        <li>
                            <a href="https://www.instagram.com/trek_tribe/" class="icon alt fab fa-instagram"
                                target="_blank">
                                <span class="label">Instagram</span>
                            </a>
                        </li>
                        <li>
                            <a href="https://chat.whatsapp.com/KweLEtTDjzjLcXBpOh2t7f" class="icon alt fab fa-whatsapp"
                                target="_blank">
                                <span class="label">Instagram</span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/TrekTribe/" class="icon alt fab fa-github" target="_blank">
                                <span class="label">GitHub</span>
                            </a>
                        </li>
                    </ul>
                </section>
            </section>
        </footer>

        <!-- Copyright -->
        <div id="copyright">
            <ul>
                <li>&copy; {% now "Y" %} TrekTribe</li>
                <li>Design: <a href="https://html5up.net">HTML5 UP</a></li>
            </ul>
        </div>

    </div>

    <!-- Scripts -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>

</html>

trektribe/templates/trektribe/event_detail.html
{% extends 'trektribe/base.html' %}
{% load static %}

{% block title %}
<title>{{ event.title }}{% if event.date %} - {{ event.date }}{% endif %} - TrekTribe</title>
{% endblock %}

{% block styles %}
{% if event.gpx_track %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
    integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
<style>
    .map {
        width: 100%;
        height: 500px;
    }

    .elevation-profile-container {
        width: 100%;
        height: 200px;
    }
</style>
{% endif %}
{% endblock %}

{% block content %}
<article class="post featured">
    <header class="major">
        {% if event.date %}
        <span class="date">{{ event.date }}</span>
        {% endif %}
        <h2><a href="{% url 'event_detail' pk=event.pk %}">{{ event.title }}</a></h2>
        {% if event.user.user_profile.display_name %}
        <span class="author">
            Autore:
            <a href="{% url 'user_profile_detail' pk=event.user.user_profile.id %}">
                {{ event.user.user_profile.display_name }}
            </a>
        </span>
        {% endif %}
        <div>{{ event.short_description|linebreaksbr}}</div>
    </header>
    {% if event.whatsapp_group and event.date and not event.is_past_due %}
    <h3 class="align-center">
        &gt;&gt;&gt;
        <a href="{{ event.whatsapp_group }}" target="_blank">
            <i class="fab fa-whatsapp"></i>
            Gruppo WhatsApp
        </a>
        &lt;&lt;&lt;
    </h3>
    {% endif %}

    <table>
        <tbody>
            {% if event.distance or event.gpx_track %}
            <tr>
                <th>Distanza</th>
                <td>
                    <span id="gpx-distance">{{ event.distance }}</span> km
                </td>
            </tr>
            {% endif %}
            {% if event.elevation_gain or event.gpx_track %}
            <tr>
                <th>Dislivello</th>
                <td>
                    <span id="gpx-elevation-gain">{{ event.elevation_gain }}</span> m D+
                </td>
            </tr>
            {% endif %}
            {% if event.starting_altitude or event.gpx_track %}
            <tr>
                <th>Altitudine alla partenza</th>
                <td>
                    <span id="gpx-elevation-start">{{ event.starting_altitude }}</span> m
                </td>
            </tr>
            {% endif %}
            {% if event.max_altitude or event.gpx_track %}
            <tr>
                <th>Altitudine max</th>
                <td>
                    <span id="gpx-elevation-max">{{ event.max_altitude }}</span> m
                </td>
            </tr>
            {% endif %}
            {% if event.difficulty %}
            <tr>
                <th>Difficoltà</th>
                <td>
                    {{ event.difficulty }}
                    {% if event.difficulty_details %}
                    <div class="details">{{ event.difficulty_details|linebreaksbr }}</div>
                    {% endif %}
                </td>
            </tr>
            {% endif %}
        </tbody>
    </table>

    {% if event.gpx_track %}
    <div id="map" class="map align-center"></div>
    <div class="elevation-profile-container align-center">
        <canvas id="route-elevation-chart" style="width:100%;height:100%"></canvas>
    </div>
    <div class="align-center">
        <a href="{{ event.gpx_track.url }}" class="button primary" target="_blank">
            <i class="fas fa-cloud-download-alt"></i>
            Scarica traccia GPX
        </a>

        <button onclick="centerMap()">Ripristina visualizzazione mappa</button>
    </div>
    {% endif %}
    <div class="event-description">{{ event.description|safe }}</div>
    <!-- <a href="#" class="image main"><img src="{% static 'images/pic01.jpg' %}" alt="" /></a> -->
</article>
{% endblock %}

{% block scripts %}
{% if event.gpx_track %}
<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
    integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.7.0/gpx.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.min.js"></script>
<script>
    /**
     * Refs:
     * - https://leafletjs.com/index.html
     * - https://github.com/mpetazzoni/leaflet-gpx
     */
    var map = L.map('map').setView([44.400, 7.50], 9);

    var lastEvent = null;
    function centerMap() {
        map.fitBounds(lastEvent.target.getBounds());
    }

    var resizeTimeout;
    function handleResize() {
        // clearTimeout(resizeTimeout);
        // resizeTimeout = setTimeout(centerMap, 500);
    }

    L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png', {
        maxZoom: 17,
        attribution: 'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, <a href="http://viewfinderpanoramas.org">SRTM</a> | Map style: &copy; <a href="https://opentopomap.org">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
    }).addTo(map);
    var marker = L.circleMarker().setRadius(5);

    var gpxFile = "{{ event.gpx_track.url }}"; // URL to your GPX file or the GPX itself
    var gpx = new L.GPX(gpxFile, {
        async: true,
        marker_options: {
            startIconUrl: "{% static 'images/pin-icon-start.png' %}",
            endIconUrl: "{% static 'images/pin-icon-end.png' %}",
            shadowUrl: "{% static 'images/pin-shadow.png' %}",
            wptIconUrl: "{% static 'images/pin-icon-wpt.png' %}",
            wptIconUrls: { "": "{% static 'images/pin-icon-start.png' %}" },
        }
    });
    gpx.on('loaded', (e) => {
        const ctx = document.getElementById("route-elevation-chart").getContext("2d");
        const elevationData = e.target.get_elevation_data();
        const chartData = {
            labels: elevationData.map(([distance, value, tooltip]) => distance),
            datasets: [{
                data: elevationData.map(([distance, value, tooltip]) => value),
                fill: true,
                borderColor: '#66ccff',
                backgroundColor: '#66ccff66',
                tension: 0.1,
                pointRadius: 0,
                spanGaps: true
            }]
        };
        const config = {
            type: 'line',
            data: chartData,
            plugins: [{
                beforeInit: (chart, args, options) => {
                    const maxHeight = Math.max(...chart.data.datasets[0].data);
                    chart.options.scales.x.min = Math.min(...chart.data.labels);
                    chart.options.scales.x.max = Math.max(...chart.data.labels);
                    chart.options.scales.y.max = maxHeight + Math.round(maxHeight * 0.2);
                },
                beforeEvent(chart, args, pluginOptions) {
                    const event = args.event;
                    if (event.type === "mouseout") {
                        marker.removeFrom(map);
                    }
                }
            }],
            options: {
                animation: false,
                maintainAspectRatio: false,
                interaction: { intersect: false, mode: 'index' },
                tooltip: { position: 'nearest' },
                scales: {
                    x: { type: 'linear' },
                    y: { type: 'linear', beginAtZero: false },
                },
                plugins: {
                    title: { align: "end", display: true, text: "Distanza, km / Altitudine, m" },
                    legend: { display: false },
                    tooltip: {
                        displayColors: false,
                        callbacks: {
                            title: (tooltipItems) => {
                                return "Distance: " + tooltipItems[0].label + 'km'
                            },
                            label: (tooltipItem) => {
                                return "Elevation: " + tooltipItem.raw + 'm'
                            },
                        }
                    }
                },
                events: ["mousemove", "mouseout", "touchstart", "touchmove"],
                onHover: (e, i) => {
                    const selectedIndex = i[0].index;
                    const gpxLatLng = gpx.getLayers()[0].getLayers()[0].getLatLngs()[selectedIndex];
                    marker.setLatLng(gpxLatLng).addTo(map);
                },
            }
        };
        const chart = new Chart(ctx, config);
        {% if not event.distance %}
        const gpxDistance = document.getElementById("gpx-distance");
        const distance = Math.round(e.target.get_distance() / 100) / 10;
        gpxDistance.textContent = distance;
        {% endif %}

        {% if not event.elevation_gain %}
        const gpxElevationGainLoss = document.getElementById("gpx-elevation-gain");
        gpxElevationGainLoss.textContent = Math.round(e.target.get_elevation_gain());
        {% endif %}

        {% if not event.starting_altitude %}
        const gpxElevationStart = document.getElementById("gpx-elevation-start");
        gpxElevationStart.textContent = Math.round(elevationData[0][1]);
        {% endif %}

        {% if not event.max_altitude %}
        const gpxElevationMax = document.getElementById("gpx-elevation-max");
        gpxElevationMax.textContent = Math.round(e.target.get_elevation_max());
        {% endif %}

        lastEvent = e;
        centerMap();
    }).addTo(map);
</script>
{% endif %}
{% endblock %}

trektribe/templates/trektribe/info.html
{% extends 'trektribe/base.html' %}
{% load static %}

{% block title %}
<title>TrekTribe - Info</title>
{% endblock %}

{% block content %}
<article class="post featured">
    <header class="major">
        <h2>
            Che cos'è TrekTribe?
        </h2>
        <h3>Apertura, libertà, opportunità</h3>
    </header>

    <p>
        TrekTribe è nato con una visione audace: rendere tutto open-source e disponibile a chiunque sia appassionato di
        escursionismo.
    </p>

    <p>
        Siamo fermamente convinti che l'avventura dovrebbe essere un diritto di tutti, senza alcuna barriera.<br>
        Perciò, offriamo un ambiente in cui chiunque può proporre e organizzare camminate, senza restrizioni o vincoli.
    </p>

    <p>
        Ciò che rende TrekTribe unico è la sua natura libera. Crediamo fortemente nella libertà di espressione e
        nell'autonomia dei singoli.<br>
        Non ci sono leader dominanti o gerarchie oppressive all'interno del nostro gruppo.<br>
        <strong>
            Ognuno di voi è libero di esprimere la propria creatività e di condividere le proprie idee.
        </strong>
    </p>

    <p>
        Entra in TrekTribe e abbraccia l'essenza dell'avventura condivisa.
        Fai parte di una comunità inclusiva che valorizza la libertà e l'esplorazione senza limiti.
        Unisciti a noi oggi stesso!
    </p>
</article>
{% endblock %}

trektribe/templates/trektribe/user_profile_detail.html
{% extends 'trektribe/base.html' %}
{% load static %}

{% block title %}
<title>Utente: {{ user_profile.display_name }} - TrekTribe</title>
{% endblock %}

{% block content %}
<article class="post featured">
    <header class="major">
        <h2>
            <a href="{% url 'user_profile_detail' pk=user_profile.pk %}">
                {{ user_profile.display_name }}
            </a>
        </h2>

        {% if user_profile.user.event_set.count > 0 %}
        <span class="author">
            Escursioni proposte: {{ user_profile.user.event_set.count }}
        </span>
        {% endif %}

        <ul class="icons alt">
            {% for link in user_profile.social_links.all %}
            <li>
                <a href="{{ link.url }}" class="icon profile-icon" target="_blank" title="{{ link.get_link_type_display }}">
                    {% if link.link_type in link_types_with_related_icon %}
                    <i class="fab fa-{{ link.link_type }}"></i>
                    {% else %}
                    <i class="fas fa-link"></i>
                    {% endif %}
                </a>
            </li>
            {% endfor %}
        </ul>

        <div>{{ user_profile.bio|safe}}</div>
    </header>
</article>
{% endblock %}